version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'kanbanDB'
    environment:
      - MONGO_INITDB_DATABASE=kanban
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=kanban123
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongodb:/data/db
    ports:
      - '27017:27017'